- README.md
- scripts/postbuild.js
-   [ ] Bugfix
-   [x] Other... Please describe:
-   [ ] Yes
-   [x] No
> update postbuild script and fix badges in README

- README.md
- projects/common/src/public-api.ts
- projects/common/src/tokens/animation-frame.ts
- projects/common/src/tokens/performance.ts
- projects/common/src/tokens/tests/animation-frame.spec.ts
- projects/common/src/tokens/tests/performance.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat(ANIMATION_FRAME): add new token

- projects/common/src/tokens/css.ts
- projects/common/src/tokens/tests/css.spec.ts
- tslint.json
-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> feat(CSS): add new token

- README.md
- projects/common/src/tokens/page-visibility.ts
- projects/common/src/tokens/tests/page-visibility.spec.ts
-   [ ] Bugfix
Added wrapper for document.addEventListener('visibilitychange') in angular token style.
-   [ ] Yes
-   [x] No
> Add token for page visibility state observing.

- README.md
- projects/common/src/public-api.ts
- projects/common/src/tokens/session-storage.ts
- projects/common/src/tokens/tests/session-storage.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> fix(SESSION_STORAGE): add new token

- CHANGELOG.md
- README.md
- projects/common/src/public-api.ts
- projects/common/src/tokens/speech-synthesis.ts
- projects/common/src/tokens/tests/speech-synthesis.spec.ts
-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> feat(SPEECH_SYNTHESIS): add new token

- README.md
- projects/common/src/public-api.ts
- projects/common/src/tokens/speech-recognition.ts
- projects/common/src/tokens/tests/speech-recognition.spec.ts
-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> feat(SPEECH_RECOGNITION): add new token

- README.md
-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> docs(README): upgrade

- README.md
- projects/common/src/public-api.ts
- projects/common/src/tokens/animation-frame.ts
- projects/common/src/tokens/caches.ts
- projects/common/src/tokens/tests/caches.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat(CACHES): add new token

- README.md
- projects/common/src/public-api.ts
- projects/common/src/tokens/history.ts
- projects/common/src/tokens/tests/history.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat(common): `HISTORY` token

- README.md
- projects/common/src/public-api.ts
- projects/common/src/tokens/media-devices.ts
- projects/common/src/tokens/tests/media-devices.spec.ts
-   [ ] Bugfix
Currently there is no MEDIA_DEVICES token.
Closes #32
Added the MEDIA_DEVICES token.
-   [ ] Yes
-   [x] No
> feat(MEDIA_DEVICES): added new token

- README.md
- projects/common/src/public-api.ts
- projects/common/src/tokens/screen.ts
- projects/common/src/tokens/tests/screen.spec.ts
-   [ ] Bugfix
Issue Number: [41](https://github.com/ng-web-apis/common/issues/41)
-   [ ] Yes
-   [x] No
> feat(screen): added new token

- apps/demo/src/app/app.routes.ts
- apps/demo/src/app/constants/demo-path.ts
- apps/demo/src/pages/home/home-page.component.html
- apps/demo/src/pages/home/home-page.component.ts
> refactor: routes

- package.json
> refactor: commands

- libs/intersection-observer/src/services/intersection-observer.service.ts
> refactor: added an optional chaining

- .github/workflows/build-prerender.yml
- libs/universal/mocks.js
- libs/universal/ng-package.json
- libs/universal/src/index.ts
- tsconfig.json
> fix(universal): add secondary entry point for mocks

- .github/workflows/release.yml
> ci: fix yml

- libs/view-transition/project.json
cant deploy package view-transition
package view-transition should be deployeable
> fix: view transition deploy

- apps/demo/src/app/pages/view-transition/view-transition-page.component.html
- package-lock.json
- package.json
> chore: ngx-highlightjs

- libs/audio/src/directives/audio-context.ts
- libs/audio/src/directives/channel.ts
- libs/audio/src/directives/destination.ts
- libs/audio/src/directives/listener.ts
- libs/audio/src/directives/offline-audio-context.ts
- libs/audio/src/directives/output.ts
- libs/audio/src/directives/stream-destination.ts
- libs/audio/src/module.ts
- libs/audio/src/nodes/analyser.ts
- libs/audio/src/nodes/biquad-filter.ts
- libs/audio/src/nodes/channel-merger.ts
- libs/audio/src/nodes/channel-splitter.ts
- libs/audio/src/nodes/convolver.ts
- libs/audio/src/nodes/delay.ts
- libs/audio/src/nodes/dynamics-compressor.ts
- libs/audio/src/nodes/gain.ts
- libs/audio/src/nodes/iir-filter.ts
- libs/audio/src/nodes/panner.ts
- libs/audio/src/nodes/script-processor.ts
- libs/audio/src/nodes/stereo-panner.ts
- libs/audio/src/nodes/wave-shaper.ts
- libs/audio/src/nodes/worklet.ts
- libs/audio/src/pipes/audio-param.pipe.ts
- libs/audio/src/pipes/periodic-wave.pipe.ts
- libs/audio/src/sources/buffer-source.ts
- libs/audio/src/sources/constant-source.ts
- libs/audio/src/sources/media-source.ts
- libs/audio/src/sources/media-stream-source.ts
- libs/audio/src/sources/oscillator.ts
> feat(audio): move to standalone

- apps/demo/server.ts
- libs/audio/README.md
- libs/audio/mocks.js
- libs/audio/src/directives/audio-context.ts
- libs/intersection-observer/README.md
- libs/intersection-observer/src/classes/safe-observer.ts
- libs/intersection-observer/src/directives/intersection-observer.directive.ts
- libs/intersection-observer/src/services/intersection-observer.service.ts
- libs/intersection-observer/tests/intersection-observer.service.spec.ts
- libs/mutation-observer/src/classes/safe-observer.ts
- libs/mutation-observer/src/directives/mutation-observer.directive.ts
- libs/mutation-observer/src/services/mutation-observer.service.ts
- libs/resize-observer/src/classes/safe-observer.ts
- libs/resize-observer/src/services/resize-observer.service.ts
- libs/resize-observer/tests/resize-observer.service.spec.ts
- libs/universal/README.md
> feat(universal): bundle mocks with the related libs and remove global `mocks.js`

- libs/intersection-observer/src/classes/safe-observer.ts
- libs/intersection-observer/src/directives/intersection-observer.directive.ts
- libs/intersection-observer/src/services/intersection-observer.service.ts
- libs/intersection-observer/src/tokens/support.ts
- libs/intersection-observer/tests/intersection-observer.service.spec.ts
> feat(intersection-observer): migrate to SafeObserver

- libs/intersection-observer/src/module.ts
- package-lock.json
> fix: compat for legacy modules

- libs/mutation-observer/src/classes/safe-observer.ts
- libs/mutation-observer/src/directives/mutation-observer.directive.ts
- libs/mutation-observer/src/services/mutation-observer.service.ts
> Switch to SafeObserver in MutationObserver classes to prevent errors during SSR

- .gitignore
- libs/audio/project.json
- libs/canvas/project.json
- libs/common/project.json
- libs/geolocation/project.json
- libs/intersection-observer/project.json
- libs/midi/project.json
- libs/mutation-observer/project.json
- libs/payment-request/project.json
- libs/permissions/project.json
- libs/resize-observer/project.json
- libs/speech/project.json
- libs/storage/project.json
- libs/universal/project.json
- libs/workers/project.json
- package.json
Close https://github.com/taiga-family/ng-web-apis/issues/657
> ci: correct tag version

- package.json
Closes https://github.com/taiga-family/ng-web-apis/issues/652
> chore: fix build command

- libs/platform/package.json
- package-lock.json
> fix: typo platform package name

- libs/platform/src/constants.ts
- libs/platform/tests/is-ios.spec.ts
- libs/platform/tests/is-mobile.spec.ts
> fix(platform): invalid regexp for ios

- libs/screen-orientation/src/viewport.service.ts
> fix(screen-orientation): `Viewport` fix initial value

- libs/screen-orientation/package.json
> chore: update packages readme links

- libs/resize-observer/README.md
> chore: update readme
